language: node_js
node_js:
  - "6.4.0"
script:
  - echo "Deploing!"
  - npm install
  - ng build --prod
install:
  - npm install -g firebase-tools
  - npm install -g angular-cli
after_success:
  - firebase deploy --token $FIREBASE_TOKEN